### ISSUE TITLE
Placeholders and colors not populating as expected.

### ISSUE THREAD

**Issue by loudambiance** [OGBlackDiamond/Proxy-Messages#1]
In trying to setup Proxy-Messages, I've run into an issue where colors don't work and the {cur} tag is not populated on join and leave. It also appears to always select the first message.

My config looks like:
```yaml
join-message-options:
  - "{#00ff00}>>> {cur} >>>:{#ffffff} {player} joined"
  - "{#00ff00}>>> {cur} >>>:{#ffffff} OMG EVERYONE! {player} graced us with their pressence!"
  - "{#00ff00}>>> {cur} >>>:{#ffffff} {player} is here, now the party can start!"
  - "{#00ff00}>>> {cur} >>>:{#ffffff} SHHHHH, {player} is here, everybody hide"

leave-message-options:
  - "{#ff0000}<<< {cur} <<<:{#ffffff} {player} left"
  - "{#ff0000}<<< {cur} <<<:{#ffffff} Bye Felicia! I mean {player}."
  - "{#ff0000}<<< {cur} <<<:{#ffffff} Parties over, {player} left."

switch-message-options:
  - "{#0000FF}{prev} >>> {cur}:{#ffffff} {player} changed their mind"
```

and causes output like:
![image](https://github.com/user-attachments/assets/ebb44a73-159b-4f84-85ff-d0f25ce0cb43)
and
![image](https://github.com/user-attachments/assets/fb322928-9f36-4546-957f-1f0d697443f9)
